version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    container_name: jarvis-app
    restart: always
    environment:
      POSTGRES_USER: postgresuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: aitododb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: